Repository fga-eps-mds/2019.2-Amika-Wiki, pull requests merged in 2019-10, with the labels that each got.

#92 [DOC26] Adicionando EVM
  docs/projeto/evm.md
  sidebar.md
Labels: EPS, Product Owner, documentation

#93 [DOC 31] Adiciona roadmap do DevOps
  assets/img/roadmaps/Roadmap_devops_r1.png
  assets/img/roadmaps/Roadmap_devops_r2.png
  assets/img/roadmaps/Roadmap_po_r1.png
  assets/img/roadmaps/Roadmap_po_r2.png
  assets/img/roadmaps/Roadmap_sm_r1.png
  assets/img/roadmaps/Roadmap_sm_r2.png
  assets/img/roadmaps/roadmapProduto.png
  docs/roadmap/roadmapPapeis.md
  docs/roadmap/roadmapProduto.md
  sidebar.md
Labels: DevOps, EPS, documentation, enhancement

#95 DOC06 protótipo de alta fidelidade
  docs/projeto/prototipo.md
  sidebar.md
Labels: MDS, good first issue

#102 [DOC43] Documentar sprints 8 e 9
  assets/img/burndown/burndown8.png
  assets/img/burndown_risco/burndown_risco8.png
  assets/img/quadro_conhecimento/quadro_conhecimento8.png
  assets/img/velocity/velocity8.png
  sprints/indice.md
  sprints/sprint8/planejamento.md
  sprints/sprint8/resultado.md
  sprints/sprint9/planejamento.md
Labels: EPS, Scrum Master, documentation

#109 [DOC37] Adicionando Plano de Gerencia da Qualidade
  docs/projeto/plano_qualidade.md
  sidebar.md
Labels: EPS, Product Owner, documentation

#108 [DOC38] Adicionando documento de requisitos não funcionais
  assets/img/nfr_interface.png
  assets/img/nfr_manutenabilidade.png
  assets/img/nfr_suportabilidade.png
  assets/img/nfr_usabilidade.png
  docs/projeto/nfr.md
  sidebar.md
Labels: EPS, Product Owner, documentation

#112 Adicionado o template de requisição de refatoração de documentação.
  .github/ISSUE_TEMPLATE/requisitar-refatora--o-de-documentos.md
Labels: documentation, easy to solve, enhancement

#117 Arrumando link para versao 1 backlog
  docs/projeto/backlog.md
Labels: bug, documentation

#118 Issue 115 Refatorar Roadmap
  assets/img/roadmaps/roadmapProdutov2.PNG
  docs/roadmap/roadmapProduto.md
Labels: Product Owner, documentation, refactoring

#122 [DOC39] Plano de Testes de Usabilidade
  docs/projeto/testesUsabilidade.md
  sidebar.md
Labels: Product Owner, documentation

#121 Issue 120 Adicionar Treinamentos
  docs/treinamentos/codeacademy.md
  docs/treinamentos/djangoRest.md
  docs/treinamentos/docker.md
  docs/treinamentos/gitflow.md
  docs/treinamentos/metodologiasAgeis.md
  docs/treinamentos/simulacao.md
  sidebar.md
Labels: DevOps, EPS, Product Owner, Scrum Master, documentation, training

#124 Doc44 documentar sprints
  assets/img/burndown/burndown9.png
  assets/img/burndown_risco/burndown_risco9.png
  assets/img/quadro_conhecimento/quadro_conhecimento9.png
  assets/img/velocity/velocity9.png
  sprints/indice.md
  sprints/sprint10/planejamento.md
  sprints/sprint9/planejamento.md
  sprints/sprint9/resultado.md
Labels: EPS, Scrum Master, documentation
