Repository fga-eps-mds/2019.2-Amika-Wiki, pull requests merged in 2019-11, with the labels that each got.

#128 [DOC46] Documentar sprints 11 e 12
  assets/img/burndown/burndown11.png
  assets/img/burndown_risco/burndown_risco11.png
  assets/img/quadro_conhecimento/quadro_conhecimento11.png
  assets/img/velocity/velocity11.png
  sprints/indice.md
  sprints/sprint11/resultado.md
  sprints/sprint12/planejamento.md
Labels: Scrum Master, documentation

#130 [DOC47] Documentar sprints 12 e 13
  assets/img/burndown/burndown12.png
  assets/img/burndown_risco/burndown_risco12.png
  assets/img/quadro_conhecimento/quadro_conhecimento12.png
  assets/img/velocity/velocity12.png
  sprints/indice.md
  sprints/sprint10/resultado.md
  sprints/sprint11/resultado.md
  sprints/sprint12/planejamento.md
  sprints/sprint12/resultado.md
  sprints/sprint13/planejamento.md
  sprints/sprint6/resultado.md
  sprints/sprint7/resultado.md
  sprints/sprint8/planejamento.md
  sprints/sprint8/resultado.md
  sprints/sprint9/planejamento.md
  sprints/sprint9/resultado.md
Labels: EPS, Scrum Master, documentation

#132 Issue 131 resultado teste usabilidade
  docs/projeto/resultadoTesteUsabilidade.md
  docs/projeto/testesUsabilidade.md
  sidebar.md
Labels: Product Owner, documentation

#136 [DOC48] documentar sprints 13 e 14
  assets/img/burndown/burndown13.png
  assets/img/burndown_risco/burndown_risco13.png
  assets/img/quadro_conhecimento/quadro_conhecimento12.png
  assets/img/quadro_conhecimento/quadro_conhecimento13.png
  assets/img/velocity/velocity13.png
  sprints/indice.md
  sprints/sprint13/planejamento.md
  sprints/sprint13/resultado.md
  sprints/sprint14/planejamento.md
Labels: EPS, Scrum Master, documentation

#139 Atualizando EVM
  docs/projeto/evm.md
Labels: Product Owner, documentation, refactoring

#140 Alterando estrutura do pages
  _coverpage.md
  assets/img/background.png
  docs/projeto/evm.md
  docs/projeto/r2.md
  index.html
  sidebar.md
Labels: enhancement, refactoring

#142 [HOTFIX] Ajustando links da navbar
  index.html
Labels: bug

#144 [DOC14] Adicionando resultado da sprint 14
  assets/img/burndown/burndown14.png
  assets/img/burndown_risco/burndown_risco14.png
  assets/img/quadro_conhecimento/quadro_conhecimento14.png
  assets/img/velocity/velocity14.png
  sprints/indice.md
  sprints/sprint14/resultado.md
Labels: Scrum Master, documentation
